In [1]:
from src.io_utils import load_data

df = load_data("data/ecommerce_sales.csv")
display(df.head())
print(df.shape)
print(df.columns.tolist())

   order_id       date       city     category   price  units  revenue
0    100000 2024-04-19  Stockholm       Sports  530.95      4  2123.80
1    100001 2024-05-06      Malmö       Sports  653.28      3  1959.84
2    100002 2024-03-07    Uppsala     Clothing  177.98      4   711.92
3    100003 2024-04-08   Göteborg         Home  348.57      3  1045.71
4    100004 2024-01-18    Uppsala  Electronics  777.07      3  2331.21

(2500, 7)
['order_id', 'date', 'city', 'category', 'price', 'units', 'revenue']

In [2]:
from src.metrics import calculate_total_revenue

total_revenue = calculate_total_revenue(df)
print("total revenue  ", total_revenue)
print("assert  ", df["revenue"].sum())

total revenue   3502767.23
assert   3502767.2300000004

In [3]:
from src.metrics import count_orders

result = count_orders(df)
print("number of orders  ", result)
print("assert  ", df["order_id"].nunique())

number of orders   2500
assert   2500

In [5]:
from src.metrics import calculate_aov

result = calculate_aov(df)

expected = df["revenue"].sum() / df["order_id"].nunique()
print("AOV  ", result)
print("assert  ", expected )

AOV   1401.106892
assert   1401.1068920000002

In [7]:
from src.metrics import calculate_order_ranges

result = calculate_order_ranges(df)

display(result)

print("number of groups  ", len(result))
print("assert  ", result["percentages"].sum())

                   number of orders  percentages
revenue_group
50.00 - 465.48                  484        19.36
465.48 - 880.95                 539        21.56
880.95 - 1296.43                435        17.40
1296.43 - 5244.51              1005        40.20
5244.51 - 9192.60                37         1.48

number of groups   5
assert   100.00000000000001